name: golangci-lint

on: [workflow_dispatch, pull_request]

env:
  GOLANGCI_TIMEOUT: 1m0s

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Action page: https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout ${{ env.GOLANGCI_TIMEOUT }}
          only-new-issues: true
